//------------------------------------------------------------------------
// axi_bridge_top.sv
// Real DUT wrapper: instantiates axi_slave (slave_all.v) directly.
// axi_slave is a complete, self-contained top module already present in
// the RTL - confirmed by identical port shape to axi_master and by
// tracing its internal AUTOINST hierarchy (regs_slave_inst,
// user_slave_control_inst confirmed under
// i_axi4_slave.i_axi_slave_allprot). No hand-built integration needed
// here; this is pass-through parameterization only.
//------------------------------------------------------------------------
module axi_bridge_top #(
  parameter string AXI_PROTOCOL      = "AXI4",
  parameter int    S_AXI_ADDR_WIDTH  = 64,
  parameter int    S_AXI_DATA_WIDTH  = 32,
  parameter int    M_AXI_ADDR_WIDTH  = 64,
  parameter int    M_AXI_DATA_WIDTH  = 128,
  parameter int    M_AXI_ID_WIDTH    = 16,
  parameter int    M_AXI_USER_WIDTH  = 32,
  parameter int    S_AXI_USR_ADDR_WIDTH     = 64,
  parameter int    S_AXI_USR_DATA_WIDTH     = 128,
  parameter int    S_AXI_USR_ID_WIDTH       = 16,
  parameter int    S_AXI_USR_AWUSER_WIDTH   = 32,
  parameter int    S_AXI_USR_WUSER_WIDTH    = 32,
  parameter int    S_AXI_USR_BUSER_WIDTH    = 32,
  parameter int    S_AXI_USR_ARUSER_WIDTH   = 32,
  parameter int    S_AXI_USR_RUSER_WIDTH    = 32,
  parameter int    RAM_SIZE          = 16384,
  parameter int    MAX_DESC          = 16,
  parameter int    USR_RST_NUM       = 4,
  parameter bit    PCIE_AXI          = 0,
  parameter bit    PCIE_LAST_BRIDGE  = 0,
  parameter bit    LAST_BRIDGE       = 0,
  parameter bit    EXTEND_WSTRB      = 1
) (
  input  logic axi_aclk,
  input  logic axi_aresetn,
  output logic [USR_RST_NUM-1:0] usr_resetn,     // output of the DUT, not an input

  output logic irq_out,
  input  logic irq_ack,
  output logic [127:0] h2c_intr_out,
  input  logic [63:0]  c2h_intr_in,
  output logic [63:0]  h2c_pulse_out,
  input  logic [255:0] c2h_gpio_in,
  output logic [255:0] h2c_gpio_out,

  // S_AXI - AXI4-Lite (config/descriptor access)
  input  logic [S_AXI_ADDR_WIDTH-1:0]   s_axi_awaddr,
  input  logic [2:0]                    s_axi_awprot,
  input  logic                          s_axi_awvalid,
  output logic                          s_axi_awready,
  input  logic [S_AXI_DATA_WIDTH-1:0]   s_axi_wdata,
  input  logic [(S_AXI_DATA_WIDTH/8)-1:0] s_axi_wstrb,
  input  logic                          s_axi_wvalid,
  output logic                          s_axi_wready,
  output logic [1:0]                    s_axi_bresp,
  output logic                          s_axi_bvalid,
  input  logic                          s_axi_bready,
  input  logic [S_AXI_ADDR_WIDTH-1:0]   s_axi_araddr,
  input  logic [2:0]                    s_axi_arprot,
  input  logic                          s_axi_arvalid,
  output logic                          s_axi_arready,
  output logic [S_AXI_DATA_WIDTH-1:0]   s_axi_rdata,
  output logic [1:0]                    s_axi_rresp,
  output logic                          s_axi_rvalid,
  input  logic                          s_axi_rready,

  // S_AXI_USR - full AXI4/AXI3 slave (real data-plane path, bridged to M_AXI)
  input  logic [S_AXI_USR_ID_WIDTH-1:0]     s_axi_usr_awid,
  input  logic [S_AXI_USR_ADDR_WIDTH-1:0]   s_axi_usr_awaddr,
  input  logic [7:0]                        s_axi_usr_awlen,
  input  logic [2:0]                        s_axi_usr_awsize,
  input  logic [1:0]                        s_axi_usr_awburst,
  input  logic                              s_axi_usr_awlock,
  input  logic [3:0]                        s_axi_usr_awcache,
  input  logic [2:0]                        s_axi_usr_awprot,
  input  logic [3:0]                        s_axi_usr_awqos,
  input  logic [3:0]                        s_axi_usr_awregion,
  input  logic [S_AXI_USR_AWUSER_WIDTH-1:0]  s_axi_usr_awuser,
  input  logic                              s_axi_usr_awvalid,
  output logic                              s_axi_usr_awready,
  input  logic [S_AXI_USR_DATA_WIDTH-1:0]     s_axi_usr_wdata,
  input  logic [(S_AXI_USR_DATA_WIDTH/8)-1:0] s_axi_usr_wstrb,
  input  logic                              s_axi_usr_wlast,
  input  logic [S_AXI_USR_ID_WIDTH-1:0]     s_axi_usr_wid,
  input  logic [S_AXI_USR_WUSER_WIDTH-1:0]  s_axi_usr_wuser,
  input  logic                              s_axi_usr_wvalid,
  output logic                              s_axi_usr_wready,
  output logic [S_AXI_USR_ID_WIDTH-1:0]     s_axi_usr_bid,
  output logic [1:0]                        s_axi_usr_bresp,
  output logic [S_AXI_USR_BUSER_WIDTH-1:0]  s_axi_usr_buser,
  output logic                              s_axi_usr_bvalid,
  input  logic                              s_axi_usr_bready,
  input  logic [S_AXI_USR_ID_WIDTH-1:0]     s_axi_usr_arid,
  input  logic [S_AXI_USR_ADDR_WIDTH-1:0]   s_axi_usr_araddr,
  input  logic [7:0]                        s_axi_usr_arlen,
  input  logic [2:0]                        s_axi_usr_arsize,
  input  logic [1:0]                        s_axi_usr_arburst,
  input  logic                              s_axi_usr_arlock,
  input  logic [3:0]                        s_axi_usr_arcache,
  input  logic [2:0]                        s_axi_usr_arprot,
  input  logic [3:0]                        s_axi_usr_arqos,
  input  logic [3:0]                        s_axi_usr_arregion,
  input  logic [S_AXI_USR_ARUSER_WIDTH-1:0]  s_axi_usr_aruser,
  input  logic                              s_axi_usr_arvalid,
  output logic                              s_axi_usr_arready,
  output logic [S_AXI_USR_ID_WIDTH-1:0]     s_axi_usr_rid,
  output logic [S_AXI_USR_DATA_WIDTH-1:0]   s_axi_usr_rdata,
  output logic [1:0]                        s_axi_usr_rresp,
  output logic                              s_axi_usr_rlast,
  output logic [S_AXI_USR_RUSER_WIDTH-1:0]  s_axi_usr_ruser,
  output logic                              s_axi_usr_rvalid,
  input  logic                              s_axi_usr_rready,

  // M_AXI - full AXI4 master
  output logic [M_AXI_ID_WIDTH-1:0]   m_axi_awid,
  output logic [M_AXI_ADDR_WIDTH-1:0] m_axi_awaddr,
  output logic [7:0]                  m_axi_awlen,
  output logic [2:0]                  m_axi_awsize,
  output logic [1:0]                  m_axi_awburst,
  output logic                        m_axi_awlock,
  output logic [3:0]                  m_axi_awcache,
  output logic [2:0]                  m_axi_awprot,
  output logic [3:0]                  m_axi_awqos,
  output logic [3:0]                  m_axi_awregion,
  output logic [M_AXI_USER_WIDTH-1:0] m_axi_awuser,
  output logic                        m_axi_awvalid,
  input  logic                        m_axi_awready,
  output logic [M_AXI_DATA_WIDTH-1:0]   m_axi_wdata,
  output logic [(M_AXI_DATA_WIDTH/8)-1:0] m_axi_wstrb,
  output logic                        m_axi_wlast,
  output logic [M_AXI_USER_WIDTH-1:0] m_axi_wuser,
  output logic                        m_axi_wvalid,
  input  logic                        m_axi_wready,
  input  logic [M_AXI_ID_WIDTH-1:0]   m_axi_bid,
  input  logic [1:0]                  m_axi_bresp,
  input  logic [M_AXI_USER_WIDTH-1:0] m_axi_buser,
  input  logic                        m_axi_bvalid,
  output logic                        m_axi_bready,
  output logic [M_AXI_ID_WIDTH-1:0]   m_axi_arid,
  output logic [M_AXI_ADDR_WIDTH-1:0] m_axi_araddr,
  output logic [7:0]                  m_axi_arlen,
  output logic [2:0]                  m_axi_arsize,
  output logic [1:0]                  m_axi_arburst,
  output logic                        m_axi_arlock,
  output logic [3:0]                  m_axi_arcache,
  output logic [2:0]                  m_axi_arprot,
  output logic [3:0]                  m_axi_arqos,
  output logic [3:0]                  m_axi_arregion,
  output logic [M_AXI_USER_WIDTH-1:0] m_axi_aruser,
  output logic                        m_axi_arvalid,
  input  logic                        m_axi_arready,
  input  logic [M_AXI_ID_WIDTH-1:0]   m_axi_rid,
  input  logic [M_AXI_DATA_WIDTH-1:0] m_axi_rdata,
  input  logic [1:0]                  m_axi_rresp,
  input  logic                        m_axi_rlast,
  input  logic [M_AXI_USER_WIDTH-1:0] m_axi_ruser,
  input  logic                        m_axi_rvalid,
  output logic                        m_axi_rready
);

  axi_slave #(
    .AXI_PROTOCOL       (AXI_PROTOCOL),
    .S_AXI_ADDR_WIDTH   (S_AXI_ADDR_WIDTH),
    .S_AXI_DATA_WIDTH   (S_AXI_DATA_WIDTH),
    .M_AXI_ADDR_WIDTH   (M_AXI_ADDR_WIDTH),
    .M_AXI_DATA_WIDTH   (M_AXI_DATA_WIDTH),
    .M_AXI_ID_WIDTH     (M_AXI_ID_WIDTH),
    .M_AXI_USER_WIDTH   (M_AXI_USER_WIDTH),
    .S_AXI_USR_ADDR_WIDTH   (S_AXI_USR_ADDR_WIDTH),
    .S_AXI_USR_DATA_WIDTH   (S_AXI_USR_DATA_WIDTH),
    .S_AXI_USR_ID_WIDTH     (S_AXI_USR_ID_WIDTH),
    .S_AXI_USR_AWUSER_WIDTH (S_AXI_USR_AWUSER_WIDTH),
    .S_AXI_USR_WUSER_WIDTH  (S_AXI_USR_WUSER_WIDTH),
    .S_AXI_USR_BUSER_WIDTH  (S_AXI_USR_BUSER_WIDTH),
    .S_AXI_USR_ARUSER_WIDTH (S_AXI_USR_ARUSER_WIDTH),
    .S_AXI_USR_RUSER_WIDTH  (S_AXI_USR_RUSER_WIDTH),
    .RAM_SIZE           (RAM_SIZE),
    .MAX_DESC           (MAX_DESC),
    .USR_RST_NUM        (USR_RST_NUM),
    .PCIE_AXI           (PCIE_AXI),
    .PCIE_LAST_BRIDGE   (PCIE_LAST_BRIDGE),
    .LAST_BRIDGE        (LAST_BRIDGE),
    .EXTEND_WSTRB       (EXTEND_WSTRB)
  ) dut (
    .axi_aclk      (axi_aclk),
    .axi_aresetn   (axi_aresetn),
    .usr_resetn    (usr_resetn),
    .irq_out       (irq_out),
    .irq_ack       (irq_ack),
    .h2c_intr_out  (h2c_intr_out),
    .c2h_intr_in   (c2h_intr_in),
    .h2c_pulse_out (h2c_pulse_out),
    .c2h_gpio_in   (c2h_gpio_in),
    .h2c_gpio_out  (h2c_gpio_out),
    .s_axi_awaddr  (s_axi_awaddr),  .s_axi_awprot(s_axi_awprot), .s_axi_awvalid(s_axi_awvalid), .s_axi_awready(s_axi_awready),
    .s_axi_wdata   (s_axi_wdata),   .s_axi_wstrb(s_axi_wstrb),   .s_axi_wvalid(s_axi_wvalid),   .s_axi_wready(s_axi_wready),
    .s_axi_bresp   (s_axi_bresp),   .s_axi_bvalid(s_axi_bvalid), .s_axi_bready(s_axi_bready),
    .s_axi_araddr  (s_axi_araddr),  .s_axi_arprot(s_axi_arprot), .s_axi_arvalid(s_axi_arvalid), .s_axi_arready(s_axi_arready),
    .s_axi_rdata   (s_axi_rdata),   .s_axi_rresp(s_axi_rresp),   .s_axi_rvalid(s_axi_rvalid),   .s_axi_rready(s_axi_rready),
    .s_axi_usr_awid(s_axi_usr_awid), .s_axi_usr_awaddr(s_axi_usr_awaddr), .s_axi_usr_awlen(s_axi_usr_awlen),
    .s_axi_usr_awsize(s_axi_usr_awsize), .s_axi_usr_awburst(s_axi_usr_awburst), .s_axi_usr_awlock(s_axi_usr_awlock),
    .s_axi_usr_awcache(s_axi_usr_awcache), .s_axi_usr_awprot(s_axi_usr_awprot), .s_axi_usr_awqos(s_axi_usr_awqos),
    .s_axi_usr_awregion(s_axi_usr_awregion), .s_axi_usr_awuser(s_axi_usr_awuser),
    .s_axi_usr_awvalid(s_axi_usr_awvalid), .s_axi_usr_awready(s_axi_usr_awready),
    .s_axi_usr_wdata(s_axi_usr_wdata), .s_axi_usr_wstrb(s_axi_usr_wstrb), .s_axi_usr_wlast(s_axi_usr_wlast),
    .s_axi_usr_wid(s_axi_usr_wid), .s_axi_usr_wuser(s_axi_usr_wuser),
    .s_axi_usr_wvalid(s_axi_usr_wvalid), .s_axi_usr_wready(s_axi_usr_wready),
    .s_axi_usr_bid(s_axi_usr_bid), .s_axi_usr_bresp(s_axi_usr_bresp), .s_axi_usr_buser(s_axi_usr_buser),
    .s_axi_usr_bvalid(s_axi_usr_bvalid), .s_axi_usr_bready(s_axi_usr_bready),
    .s_axi_usr_arid(s_axi_usr_arid), .s_axi_usr_araddr(s_axi_usr_araddr), .s_axi_usr_arlen(s_axi_usr_arlen),
    .s_axi_usr_arsize(s_axi_usr_arsize), .s_axi_usr_arburst(s_axi_usr_arburst), .s_axi_usr_arlock(s_axi_usr_arlock),
    .s_axi_usr_arcache(s_axi_usr_arcache), .s_axi_usr_arprot(s_axi_usr_arprot), .s_axi_usr_arqos(s_axi_usr_arqos),
    .s_axi_usr_arregion(s_axi_usr_arregion), .s_axi_usr_aruser(s_axi_usr_aruser),
    .s_axi_usr_arvalid(s_axi_usr_arvalid), .s_axi_usr_arready(s_axi_usr_arready),
    .s_axi_usr_rid(s_axi_usr_rid), .s_axi_usr_rdata(s_axi_usr_rdata), .s_axi_usr_rresp(s_axi_usr_rresp),
    .s_axi_usr_rlast(s_axi_usr_rlast), .s_axi_usr_ruser(s_axi_usr_ruser),
    .s_axi_usr_rvalid(s_axi_usr_rvalid), .s_axi_usr_rready(s_axi_usr_rready),
    .m_axi_awid(m_axi_awid), .m_axi_awaddr(m_axi_awaddr), .m_axi_awlen(m_axi_awlen), .m_axi_awsize(m_axi_awsize),
    .m_axi_awburst(m_axi_awburst), .m_axi_awlock(m_axi_awlock), .m_axi_awcache(m_axi_awcache), .m_axi_awprot(m_axi_awprot),
    .m_axi_awqos(m_axi_awqos), .m_axi_awregion(m_axi_awregion), .m_axi_awuser(m_axi_awuser),
    .m_axi_awvalid(m_axi_awvalid), .m_axi_awready(m_axi_awready),
    .m_axi_wdata(m_axi_wdata), .m_axi_wstrb(m_axi_wstrb), .m_axi_wlast(m_axi_wlast), .m_axi_wuser(m_axi_wuser),
    .m_axi_wvalid(m_axi_wvalid), .m_axi_wready(m_axi_wready),
    .m_axi_bid(m_axi_bid), .m_axi_bresp(m_axi_bresp), .m_axi_buser(m_axi_buser), .m_axi_bvalid(m_axi_bvalid), .m_axi_bready(m_axi_bready),
    .m_axi_arid(m_axi_arid), .m_axi_araddr(m_axi_araddr), .m_axi_arlen(m_axi_arlen), .m_axi_arsize(m_axi_arsize),
    .m_axi_arburst(m_axi_arburst), .m_axi_arlock(m_axi_arlock), .m_axi_arcache(m_axi_arcache), .m_axi_arprot(m_axi_arprot),
    .m_axi_arqos(m_axi_arqos), .m_axi_arregion(m_axi_arregion), .m_axi_aruser(m_axi_aruser),
    .m_axi_arvalid(m_axi_arvalid), .m_axi_arready(m_axi_arready),
    .m_axi_rid(m_axi_rid), .m_axi_rdata(m_axi_rdata), .m_axi_rresp(m_axi_rresp), .m_axi_rlast(m_axi_rlast),
    .m_axi_ruser(m_axi_ruser), .m_axi_rvalid(m_axi_rvalid), .m_axi_rready(m_axi_rready)
  );

endmodule : axi_bridge_top
